apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: tourissmo.infra@ncs-it.pt
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tourissmo-staging-ssl
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
