name: Deploy Kubernetes Cluster

env:
  do_api_token: ${{ secrets.DO_API_TOKEN }}

on:
  push:
    branches: [master]

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -input=false -backend-config=backend.hcl

      - name: Terraform Validation
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var="do_environment=production" -var="do_vpc_ip_range=10.0.10.0/24"

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Terraform Init
      run: terraform init -input=false -backend-config=backend.hcl

    - name: Terraform Validation
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var="do_environment=production" -var="do_vpc_ip_range=10.0.10.0/24"
        -var "do_api_token=${{ secrets.DO_API_TOKEN }}"
