name: Deploy Kubernetes Cluster - Production

on:
  workflow_dispatch:

env:
  PG_CONN_STR: ${{ secrets.PG_CONN_STR }}

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validation
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
          -var="do_environment=production"
          -var="do_vpc_ip_range=10.0.10.0/24"
          -var "do_api_token=${{ secrets.DO_API_TOKEN }}"

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validation
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve
        -var="do_environment=production"
        -var="do_vpc_ip_range=10.0.10.0/24"
        -var "do_api_token=${{ secrets.DO_API_TOKEN }}"
