name: Deploy Kubernetes Cluster - Staging

env:
  do_api_token: ${{ secrets.DO_API_TOKEN }}
  PGUSER: "doadmin"
  PGPASSWORD: ${{ secrets.DO_PG_PASS }}

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - uses: actions/checkout@v3
      - name: Terraform Init
        run: export PGUSER=doadmin
          export PGPASSWORD=${{ secrets.DO_PG_PASS }}
          terraform init

      - name: Terraform Validation
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
          -var="do_environment=staging"
          -var="do_vpc_ip_range=10.0.20.0/24"

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Terraform Init
      run: export PGUSER=doadmin
        export PGPASSWORD=${{ secrets.DO_PG_PASS }}
        terraform init

    - name: Terraform Validation
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve
        -var="do_environment=staging"
        -var="do_vpc_ip_range=10.0.20.0/24"
        -var "do_api_token=${{ secrets.DO_API_TOKEN }}"
