name: Destroy Kubernetes Cluster - Production

on:
  workflow_dispatch:

env:
  PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
  do_environment: production
  do_vpc_ip_range: 10.0.10.0/24
  do_api_token: ${{ secrets.DO_API_TOKEN }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validation
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-destroy:
    runs-on: ubuntu-latest
    needs: terraform-plan
    name: Terraform Destroy

    steps:
    - uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validation
      run: terraform validate

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
